# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  issues:
    types: [opened]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ISSUE_BODY: "${{ github.event.issue.body }}"
    if: contains(github.event.issue.title, '[Project]:')
    steps:
      - name: Issue Forms Body Parser
        id: parse
        uses: zentered/issue-forms-body-parser@v2.1.1
        with:
          body: ${{ env.ISSUE_BODY }}

      - name: Tratamento de Dados
        id: dados
        run: |
          solicitante=$(echo ${{ toJSON(steps.parse.outputs.data) }} | jq .solicitante.text)
          projeto=$(echo ${{ toJSON(steps.parse.outputs.data) }} | jq .projeto.text)
          cliente=$(echo ${{ toJSON(steps.parse.outputs.data) }} | jq .cliente.text)
          email=$(echo ${{ toJSON(steps.parse.outputs.data) }} | jq .mail.text)
          
          echo "solicitante=$solicitante" >> $GITHUB_OUTPUT
          echo "projeto=$projeto" >> $GITHUB_OUTPUT
          echo "cliente=$cliente" >> $GITHUB_OUTPUT
          echo "email=$email" >> $GITHUB_OUTPUT
    
 
      - name: Gerar ID Aleatorio
        id: random
        run: |
          randname=$(echo $RANDOM | base64 | head -c 20;)
          echo "name=$randname" >> $GITHUB_OUTPUT

      - name: Criar repositório de Demo
        run: |
          gh repo create "${{ github.repository_owner }}/${{ steps.dados.outputs.projeto }}-${{ steps.dados.outputs.cliente }}-${{ steps.random.outputs.name }}" --private --template "${{ github.repository_owner }}/${{ steps.dados.outputs.projeto }}"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Permissão ao repositório Criado
        run: |
          curl -X PUT -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.GH_TOKEN }}" https://api.github.com/repos/${{ github.repository_owner }}/${{ steps.dados.outputs.projeto }}-${{ steps.dados.outputs.cliente }}-${{ steps.random.outputs.name }}/collaborators/${{ steps.participante.outputs.idparticipante }} -d '{"permission":"admin"}'
      
      - name: Permissão a secret de organização
        run: |
          repoid=$(curl -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.GH_TOKEN }}" https://api.github.com/repos/${{ github.repository_owner }}/${{ steps.dados.outputs.projeto }}-${{ steps.dados.outputs.cliente }}-${{ steps.random.outputs.name }} | jq '.id')
          curl -X PUT -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.GH_TOKEN }}" https://api.github.com/orgs/${{ github.repository_owner }}/actions/secrets/GH_TOKEN/repositories/$repoid
          curl -X PUT -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.GH_TOKEN }}" https://api.github.com/orgs/${{ github.repository_owner }}/actions/secrets/AZURE_LOGIN/repositories/$repoid


      - name: Adicionando Variaveis no Repositório
        run: |
          rgnamedev="rg-poc-dev-${{ steps.dados.outputs.cliente }}-${{ steps.random.outputs.name }}"
          rgnamehml="rg-poc-hml-${{ steps.dados.outputs.cliente }}-${{ steps.random.outputs.name }}"
          rgnameprd="rg-poc-prd-${{ steps.dados.outputs.cliente }}-${{ steps.random.outputs.name }}"

          gh secret set email --body ${{ steps.dados.outputs.email }} --repo "${{ github.repository_owner }}/${{ steps.dados.outputs.projeto }}-${{ steps.dados.outputs.cliente }}-${{ steps.random.outputs.name }}"
          gh secret set cliente --body ${{ steps.dados.outputs.cliente }} --repo "${{ github.repository_owner }}/${{ steps.dados.outputs.projeto }}-${{ steps.dados.outputs.cliente }}-${{ steps.random.outputs.name }}" 
          gh secret set projeto --body ${{ steps.dados.outputs.projeto }} --repo "${{ github.repository_owner }}/${{ steps.dados.outputs.projeto }}-${{ steps.dados.outputs.cliente }}-${{ steps.random.outputs.name }}"
          gh secret set rgnamedev --body $rgnamedev --repo "${{ github.repository_owner }}/${{ steps.dados.outputs.projeto }}-${{ steps.dados.outputs.cliente }}-${{ steps.random.outputs.name }}"
          gh secret set rgnamehml --body $rgnamehml --repo "${{ github.repository_owner }}/${{ steps.dados.outputs.projeto }}-${{ steps.dados.outputs.cliente }}-${{ steps.random.outputs.name }}"
          gh secret set rgnameprd --body $rgnameprd --repo "${{ github.repository_owner }}/${{ steps.dados.outputs.projeto }}-${{ steps.dados.outputs.cliente }}-${{ steps.random.outputs.name }}"
          gh secret set randomname --body ${{ steps.random.outputs.name }} --repo "${{ github.repository_owner }}/${{ steps.dados.outputs.projeto }}-${{ steps.dados.outputs.cliente }}-${{ steps.random.outputs.name }}"

        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
