# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  issues:
    types: [opened]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ISSUE_BODY: "${{ github.event.issue.body }}"
    if: contains(github.event.issue.title, '[Project]:')
    steps:
      - name: Issue Forms Body Parser
        id: parse
        uses: zentered/issue-forms-body-parser@v2.1.1
        with:
          body: ${{ env.ISSUE_BODY }}

      - run: |
          number='echo $(jq -r '.number' <<< "number=`echo $(jq -r '.number' <<< "$githubjson")`")'
          repo=(echo ${{ toJSON(steps.parse.outputs.data) }} | jq .projeto.text)
          solicitante=(echo ${{ toJSON(steps.parse.outputs.data) }} | jq .solicitante.text)
          cliente=(echo ${{ toJSON(steps.parse.outputs.data) }} | jq .cliente.text)
          
          echo $number - $repo - $solicitante - $cliente"
          
 
