# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  issues:
    types: [opened]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ISSUE_BODY: "${{ github.event.issue.body }}"
    if: contains(github.event.issue.title, '[Project]:')
    steps:
      - name: Issue Forms Body Parser
        id: parse
        uses: zentered/issue-forms-body-parser@v2.1.1
        with:
          body: ${{ env.ISSUE_BODY }}

      - name: Tratamento de Dados
        id: dados
        run: |
          solicitante=$(echo ${{ toJSON(steps.parse.outputs.data) }} | jq .solicitante.text)
          projeto=$(echo ${{ toJSON(steps.parse.outputs.data) }} | jq .projeto.text)
          cliente=$(echo ${{ toJSON(steps.parse.outputs.data) }} | jq .cliente.text)
          email=$(echo ${{ toJSON(steps.parse.outputs.data) }} | jq .mail.text)
          
          echo "solicitante=$solicitante" >> $GITHUB_OUTPUT
          echo "projeto=$projeto" >> $GITHUB_OUTPUT
          echo "cliente=$cliente" >> $GITHUB_OUTPUT
          echo "email=$email" >> $GITHUB_OUTPUT
      
       - name: Login Azure
         uses: azure/login@v1
         with:
           creds: ${{ secrets.AZURE_CREDENTIALS }}
 
       - name: Gerar ID Aleatorio
         id: random
         run: |
           randname=$(echo $RANDOM | base64 | head -c 20;)
           echo "name=$randname" >> $GITHUB_OUTPUT

      #  - name: Criar repositório de Demo
      #    run: |
      #      gh repo create "${{ github.repository_owner }}/${{ steps.dados.outputs.projeto }}-${{ steps.dados.outputs.cliente }}-${{ steps.random.outputs.randname }}" --private --template "${{ github.repository_owner }}/${{ steps.dados.outputs.projeto }}"

       - name: Criar Resource Groups
         run: |
           rgnamedev="rg-poc-dev-${{ steps.dados.outputs.cliente }}-${{ steps.random.outputs.randname }}"
           rgnamehml="rg-poc-hml-${{ steps.dados.outputs.cliente }}-${{ steps.random.outputs.randname }}"
           rgnameprd="rg-poc-prd-${{ steps.dados.outputs.cliente }}-${{ steps.random.outputs.randname }}"

