# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  issues:
    types: [opened]

permissions:
  issues: write


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ISSUE_BODY: "${{ github.event.issue.body }}"
    if: contains(github.event.issue.title, '[Project]:')
    steps:
      - name: Issue Forms Body Parser
        id: parse
        uses: zentered/issue-forms-body-parser@v2.1.1
        with:
          body: ${{ env.ISSUE_BODY }}

      - name: Tratamento de Dados
        id: dados
        run: |
          solicitante=$(echo ${{ toJSON(steps.parse.outputs.data) }} | jq .solicitante.text | sed 's/"//g')
          projeto=$(echo ${{ toJSON(steps.parse.outputs.data) }} | jq .projeto.text | sed 's/"//g')
          cliente=$(echo ${{ toJSON(steps.parse.outputs.data) }} | jq .cliente.text | sed 's/"//g')
          email=$(echo ${{ toJSON(steps.parse.outputs.data) }} | jq .mail.text )
          
          echo "solicitante=$solicitante" >> $GITHUB_OUTPUT
          echo "projeto=$projeto" >> $GITHUB_OUTPUT
          echo "cliente=$cliente" >> $GITHUB_OUTPUT
          echo "email=$email" >> $GITHUB_OUTPUT
    
 
      - name: Gerar ID Aleatorio
        id: random
        run: |
          randname=$(echo $RANDOM | base64 | head -c 20;)
          echo "name=$randname" >> $GITHUB_OUTPUT

      - name: Criar repositório de Demo
        run: |
          gh repo create "${{ github.repository_owner }}/${{ steps.dados.outputs.projeto }}-${{ steps.dados.outputs.cliente }}-${{ steps.random.outputs.name }}" --public --template "${{ github.repository_owner }}/${{ steps.dados.outputs.projeto }}"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Permissão ao repositório Criado
        run: |
          curl -X PUT -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.GH_TOKEN }}" https://api.github.com/repos/${{ github.repository_owner }}/${{ steps.dados.outputs.projeto }}-${{ steps.dados.outputs.cliente }}-${{ steps.random.outputs.name }}/collaborators/${{ steps.participante.outputs.idparticipante }} -d '{"permission":"admin"}'
      
      - name: Permissão a secret de organização
        run: |
          repoid=$(curl -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.GH_TOKEN }}" https://api.github.com/repos/${{ github.repository_owner }}/${{ steps.dados.outputs.projeto }}-${{ steps.dados.outputs.cliente }}-${{ steps.random.outputs.name }} | jq '.id')
          curl -X PUT -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.GH_TOKEN }}" https://api.github.com/orgs/${{ github.repository_owner }}/actions/secrets/GH_TOKEN/repositories/$repoid
          curl -X PUT -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.GH_TOKEN }}" https://api.github.com/orgs/${{ github.repository_owner }}/actions/secrets/AZURE_LOGIN/repositories/$repoid


      - name: Adicionando Variaveis no Repositório
        run: |
          curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/${{ github.repository_owner }}/${{ steps.dados.outputs.projeto }}-${{ steps.dados.outputs.cliente }}-${{ steps.random.outputs.name }}/actions/variables -d '{"name":"email","value":"${{ steps.dados.outputs.email }}"}'
          curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/${{ github.repository_owner }}/${{ steps.dados.outputs.projeto }}-${{ steps.dados.outputs.cliente }}-${{ steps.random.outputs.name }}/actions/variables -d '{"name":"cliente","value":"${{ steps.dados.outputs.cliente }}"}'
          curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/${{ github.repository_owner }}/${{ steps.dados.outputs.projeto }}-${{ steps.dados.outputs.cliente }}-${{ steps.random.outputs.name }}/actions/variables -d '{"name":"projeto","value":"${{ steps.dados.outputs.projeto }}"}'
          curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/${{ github.repository_owner }}/${{ steps.dados.outputs.projeto }}-${{ steps.dados.outputs.cliente }}-${{ steps.random.outputs.name }}/actions/variables -d '{"name":"rgnamedev","value":"rg-poc-dev-${{ steps.dados.outputs.cliente }}-${{ steps.random.outputs.name }}"}'
          curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/${{ github.repository_owner }}/${{ steps.dados.outputs.projeto }}-${{ steps.dados.outputs.cliente }}-${{ steps.random.outputs.name }}/actions/variables -d '{"name":"rgnamehml","value":"rg-poc-hml-${{ steps.dados.outputs.cliente }}-${{ steps.random.outputs.name }}"}'
          curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/${{ github.repository_owner }}/${{ steps.dados.outputs.projeto }}-${{ steps.dados.outputs.cliente }}-${{ steps.random.outputs.name }}/actions/variables -d '{"name":"rgnameprd","value":"rg-poc-prd-${{ steps.dados.outputs.cliente }}-${{ steps.random.outputs.name }}"}'
          curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/${{ github.repository_owner }}/${{ steps.dados.outputs.projeto }}-${{ steps.dados.outputs.cliente }}-${{ steps.random.outputs.name }}/actions/variables -d '{"name":"randomname","value":"${{ steps.random.outputs.name }}"}'

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            @${{ steps.dados.outputs.solicitante }} Repositório Criado: https://github.com//${{ github.repository_owner }}${{ steps.dados.outputs.projeto }}-${{ steps.dados.outputs.cliente }}-${{ steps.random.outputs.name }}
            Esse repostório será excluido em 24h.

      - name: Close Issue
        uses: peter-evans/close-issue@v2
        with:
          issue-number: ${{ github.event.issue.number }}

          
